### ISSUE TITLE
Seg fault when starting emulation on Linux 

### ISSUE THREAD

**Issue by LittleWhite-tb** [citra-emu/citra#1242]
Hello,

I did a clean copy of the repository (with submodule). I am on Linux, using NVIDIA 360M GTS (OpenGL 3.3) : 
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTS 360M/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.93
```

citra-qt is crashing at startup after ROM (homebrew) loading :
```./citra-qt 
[   0.000000] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.config/citra-emu/qt-config.ini
[   2.090150] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.config/citra-emu/qt-config.ini
[   2.185041] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.config/citra-emu/qt-config.ini
[   3.576011] Frontend <Info> citra_qt/main.cpp:BootGame:250: Citra starting...
[   3.601538] Service.FS <Info> core/file_sys/archive_sdmc.cpp:ArchiveFactory_SDMC:21: Directory /home/alexandre/.local/share/citra-emu/sdmc/ set as SDMC.
[   3.601636] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.local/share/citra-emu/sdmc/
[   3.601699] Service.FS <Info> core/file_sys/archive_savedata.cpp:ArchiveFactory_SaveData:36: Directory /home/alexandre/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/ set as SaveData.
[   3.601745] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/alexandre/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   3.601803] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/extdata/
[   3.601843] Service.FS <Info> core/file_sys/archive_extsavedata.cpp:ArchiveFactory_ExtSaveData:62: Directory /home/alexandre/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/ set as base for ExtSaveData.
[   3.601893] Common.Filesystem <Warning> common/file_util.cpp:CreateFullPath:198: path exists /home/alexandre/.local/share/citra-emu/nand/data/00000000000000000000000000000000/extdata/
[   3.602173] Service.APT <Warning> core/hle/service/apt/apt.cpp:Init:411: Unable to load shared font: /home/alexandre/.local/share/citra-emu/sysdata/shared_font.bin
[   3.837512] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:417: GL_VERSION: 3.3.0 NVIDIA 340.93
[   3.837539] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:418: GL_VENDOR: NVIDIA Corporation
[   3.837547] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:419: GL_RENDERER: GeForce GTS 360M/PCIe/SSE2
Erreur de segmentation
```
The backtrace is the following (with the hope it can help a bit).
```
#0  0x00007ffff3940e0d in ?? () from /usr/lib64/libnvidia-glcore.so.340.93
#1  0x00007ffff39412dc in ?? () from /usr/lib64/libnvidia-glcore.so.340.93
#2  0x00000000007e91a4 in RasterizerOpenGL::SetShader (this=0x9a3e2f0)
    at /tmp/citra/src/video_core/renderer_opengl/gl_rasterizer.cpp:483
#3  0x00000000007e7a21 in RasterizerOpenGL::InitObjects (this=0x9a3e2f0)
    at /tmp/citra/src/video_core/renderer_opengl/gl_rasterizer.cpp:71
#4  0x00000000007d3f6c in RendererOpenGL::InitOpenGLObjects (this=0x9a3e1e0)
    at /tmp/citra/src/video_core/renderer_opengl/renderer_opengl.cpp:289
#5  0x00000000007d49fa in RendererOpenGL::Init (this=0x9a3e1e0)
    at /tmp/citra/src/video_core/renderer_opengl/renderer_opengl.cpp:420
#6  0x00000000007cae13 in VideoCore::Init (emu_window=0x9648ae0)
    at /tmp/citra/src/video_core/video_core.cpp:34
#7  0x00000000006ddc74 in System::Init (emu_window=0x9648ae0)
    at /tmp/citra/src/core/system.cpp:26
#8  0x0000000000660f3e in GMainWindow::BootGame (this=0x7fffffffd450, 
    filename="/share_windows/Jeux/3DS/starter/3ds/3dscraft/3dscraft.3dsx")
    at /tmp/citra/src/citra_qt/main.cpp:257
```
I tried a clean of the config files with no effect.

**Comment by mailwl** [comment]
try to update drivers (current version 340.96 for 300M series)

**Comment by LittleWhite-tb** [comment]
I did the update and same crash. If I have time, I will try to investigate properly around this one.

**Comment by LittleWhite-tb** [comment]
The bug disappeared when I updated to last version. Maybe a problem with compilation or submodule. Sorry about the useless noise.
