### ISSUE TITLE
Citra crashes when launching programs that aren't FBI from FBI

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4503]
Backtrace:
```
#0  0x0000555555669491 in void assert_noinline_call<ResultVal<boost::intrusive_ptr<Kernel::Thread> >::Unwrap() &&::{lambda()#1}>(ResultVal<boost::intrusive_ptr<Kernel::Thread> >::Unwrap() &&::{lambda()#1} const&) [clone .isra.71] ()
#1  0x00005555557bc581 in Kernel::SetupMainThread(Kernel::KernelSystem&, unsigned int, unsigned int, boost::intrusive_ptr<Kernel::Process>) ()
#2  0x000055555586de3d in Kernel::Process::Run(int, unsigned int) ()
#3  0x000055555580cba8 in Loader::AppLoader_NCCH::LoadExec(boost::intrusive_ptr<Kernel::Process>&) ()
#4  0x000055555580d413 in Loader::AppLoader_NCCH::Load(boost::intrusive_ptr<Kernel::Process>&) ()
#5  0x00005555558cf29d in Service::NS::LaunchTitle(Service::FS::MediaType, unsigned long) ()
#6  0x00005555558f3a7b in Service::APT::AppletManager::DoApplicationJump() ()
#7  0x0000555555880d93 in Service::APT::Module::Interface::DoApplicationJump(Kernel::HLERequestContext&) ()
#8  0x00005555557f9330 in Service::ServiceFrameworkBase::HandleSyncRequest(boost::intrusive_ptr<Kernel::ServerSession>) ()
#9  0x000055555587083c in Kernel::ServerSession::HandleSyncRequest(boost::intrusive_ptr<Kernel::Thread>) ()
#10 0x00005555558f12d8 in Kernel::ClientSession::SendSyncRequest(boost::intrusive_ptr<Kernel::Thread>) ()
#11 0x0000555555872c03 in Kernel::SVC::SendSyncRequest(unsigned int) ()
#12 0x000055555587a050 in void Kernel::SVCWrapper<Kernel::SVC>::Wrap<&Kernel::SVC::SendSyncRequest>() ()
#13 0x00005555558765a4 in Kernel::SVC::CallSVC(unsigned int) ()
#14 0x00007fff70203d15 in  ()
#15 0x00007fff9cae9d70 in  ()
#16 0x0000000000000000 in  ()
```
[citra_log.txt](https://github.com/citra-emu/citra/files/2675970/citra_log.txt)
[Video](https://streamable.com/a5wyb)

**Comment by FearlessTobi** [comment]
This is working without crashes now.
